"""Aisle tagging (decision Q13, hybrid philosophy).

A built-in lookup table covers common ingredients for free; unknown ingredients
get ❓ and the user's AI (or the user) assigns a tag via PATCH /ingredients.
The emoji vocabulary is part of the published skill, so AIs use the same tags.
"""

# Store-walking order — the shopping list sorts by this.
AISLES: list[tuple[str, str]] = [
    ("🥬", "Fruit & veg"),
    ("🍞", "Bakery"),
    ("🥩", "Meat & fish"),
    ("🥛", "Dairy & eggs"),
    ("🥫", "Tins & jars"),
    ("🍝", "Dry goods & pasta"),
    ("🌶️", "Herbs & spices"),
    ("🥤", "Drinks"),
    ("🍫", "Snacks"),
    ("🧊", "Frozen"),
    ("🧼", "Toiletries"),
    ("🧴", "Household"),
    ("❓", "Unknown"),
]

UNKNOWN_AISLE = "❓"
AISLE_EMOJIS = [emoji for emoji, _ in AISLES]
AISLE_ORDER = {emoji: index for index, (emoji, _) in enumerate(AISLES)}

# Keyword → aisle. Matched against whole words in the canonical ingredient
# name; longest keyword wins so "spring onion" beats "onion".
_KEYWORDS: dict[str, str] = {
    # 🥬 Fruit & veg
    "onion": "🥬",
    "spring onion": "🥬",
    "red onion": "🥬",
    "shallot": "🥬",
    "garlic": "🥬",
    "carrot": "🥬",
    "potato": "🥬",
    "sweet potato": "🥬",
    "tomato": "🥬",
    "cherry tomato": "🥬",
    "pepper": "🥬",
    "bell pepper": "🥬",
    "red pepper": "🥬",
    "chilli": "🥬",
    "chili": "🥬",
    "lettuce": "🥬",
    "cucumber": "🥬",
    "celery": "🥬",
    "leek": "🥬",
    "broccoli": "🥬",
    "cauliflower": "🥬",
    "spinach": "🥬",
    "kale": "🥬",
    "cabbage": "🥬",
    "courgette": "🥬",
    "zucchini": "🥬",
    "aubergine": "🥬",
    "eggplant": "🥬",
    "mushroom": "🥬",
    "ginger": "🥬",
    "lemon": "🥬",
    "lime": "🥬",
    "orange": "🥬",
    "apple": "🥬",
    "banana": "🥬",
    "avocado": "🥬",
    "berries": "🥬",
    "strawberry": "🥬",
    "blueberry": "🥬",
    "raspberry": "🥬",
    "grape": "🥬",
    "pear": "🥬",
    "mango": "🥬",
    "pineapple": "🥬",
    "melon": "🥬",
    "parsnip": "🥬",
    "swede": "🥬",
    "turnip": "🥬",
    "beetroot": "🥬",
    "radish": "🥬",
    "green bean": "🥬",
    "mangetout": "🥬",
    "asparagus": "🥬",
    "sweetcorn": "🥬",
    "corn": "🥬",
    "salad": "🥬",
    "rocket": "🥬",
    "watercress": "🥬",
    "herbs": "🥬",
    "coriander": "🥬",
    "parsley": "🥬",
    "basil": "🥬",
    "mint": "🥬",
    "dill": "🥬",
    "rosemary": "🥬",
    "thyme": "🥬",
    "sage": "🥬",
    "lemongrass": "🥬",
    # 🍞 Bakery
    "bread": "🍞",
    "baguette": "🍞",
    "roll": "🍞",
    "bun": "🍞",
    "burger bun": "🍞",
    "pitta": "🍞",
    "pita": "🍞",
    "wrap": "🍞",
    "tortilla": "🍞",
    "naan": "🍞",
    "croissant": "🍞",
    "bagel": "🍞",
    "brioche": "🍞",
    "crumpet": "🍞",
    "sourdough": "🍞",
    # 🥩 Meat & fish
    "beef": "🥩",
    "minced beef": "🥩",
    "beef mince": "🥩",
    "mince": "🥩",
    "steak": "🥩",
    "chicken": "🥩",
    "chicken breast": "🥩",
    "chicken thigh": "🥩",
    "turkey": "🥩",
    "pork": "🥩",
    "bacon": "🥩",
    "ham": "🥩",
    "sausage": "🥩",
    "chorizo": "🥩",
    "lamb": "🥩",
    "duck": "🥩",
    "gammon": "🥩",
    "pancetta": "🥩",
    "prosciutto": "🥩",
    "salmon": "🥩",
    "cod": "🥩",
    "haddock": "🥩",
    "tuna steak": "🥩",
    "prawn": "🥩",
    "shrimp": "🥩",
    "fish": "🥩",
    "seafood": "🥩",
    "mackerel": "🥩",
    "sea bass": "🥩",
    # 🥛 Dairy & eggs
    "milk": "🥛",
    "butter": "🥛",
    "cheese": "🥛",
    "cheddar": "🥛",
    "parmesan": "🥛",
    "mozzarella": "🥛",
    "feta": "🥛",
    "halloumi": "🥛",
    "cream": "🥛",
    "double cream": "🥛",
    "sour cream": "🥛",
    "creme fraiche": "🥛",
    "crème fraîche": "🥛",
    "yoghurt": "🥛",
    "yogurt": "🥛",
    "egg": "🥛",
    "margarine": "🥛",
    "mascarpone": "🥛",
    "ricotta": "🥛",
    # 🥫 Tins & jars
    "chopped tomatoes": "🥫",
    "tinned tomatoes": "🥫",
    "tomato puree": "🥫",
    "tomato purée": "🥫",
    "passata": "🥫",
    "baked beans": "🥫",
    "kidney beans": "🥫",
    "black beans": "🥫",
    "butter beans": "🥫",
    "cannellini beans": "🥫",
    "chickpeas": "🥫",
    "coconut milk": "🥫",
    "tuna": "🥫",
    "sweetcorn tin": "🥫",
    "olives": "🥫",
    "capers": "🥫",
    "anchovies": "🥫",
    "curry paste": "🥫",
    "pesto": "🥫",
    "mayonnaise": "🥫",
    "ketchup": "🥫",
    "mustard": "🥫",
    "soy sauce": "🥫",
    "fish sauce": "🥫",
    "worcestershire sauce": "🥫",
    "hot sauce": "🥫",
    "vinegar": "🥫",
    "balsamic vinegar": "🥫",
    "honey": "🥫",
    "jam": "🥫",
    "marmalade": "🥫",
    "peanut butter": "🥫",
    "stock": "🥫",
    "stock cube": "🥫",
    "stock pot": "🥫",
    "gravy": "🥫",
    "chutney": "🥫",
    "pickle": "🥫",
    "sauerkraut": "🥫",
    "kimchi": "🥫",
    # 🍝 Dry goods & pasta
    "pasta": "🍝",
    "spaghetti": "🍝",
    "penne": "🍝",
    "fusilli": "🍝",
    "macaroni": "🍝",
    "lasagne sheets": "🍝",
    "noodles": "🍝",
    "rice": "🍝",
    "basmati rice": "🍝",
    "risotto rice": "🍝",
    "arborio rice": "🍝",
    "couscous": "🍝",
    "quinoa": "🍝",
    "lentils": "🍝",
    "flour": "🍝",
    "plain flour": "🍝",
    "self-raising flour": "🍝",
    "sugar": "🍝",
    "caster sugar": "🍝",
    "brown sugar": "🍝",
    "icing sugar": "🍝",
    "oats": "🍝",
    "porridge": "🍝",
    "cereal": "🍝",
    "breadcrumbs": "🍝",
    "cornflour": "🍝",
    "baking powder": "🍝",
    "bicarbonate of soda": "🍝",
    "yeast": "🍝",
    "vanilla extract": "🍝",
    "olive oil": "🍝",
    "vegetable oil": "🍝",
    "sunflower oil": "🍝",
    "sesame oil": "🍝",
    "coconut oil": "🍝",
    "nuts": "🍝",
    "almonds": "🍝",
    "walnuts": "🍝",
    "cashews": "🍝",
    "peanuts": "🍝",
    "pine nuts": "🍝",
    "raisins": "🍝",
    "sultanas": "🍝",
    "dried apricots": "🍝",
    # 🌶️ Herbs & spices
    "salt": "🌶️",
    "black pepper": "🌶️",
    "paprika": "🌶️",
    "smoked paprika": "🌶️",
    "cumin": "🌶️",
    "ground cumin": "🌶️",
    "turmeric": "🌶️",
    "cinnamon": "🌶️",
    "nutmeg": "🌶️",
    "oregano": "🌶️",
    "dried oregano": "🌶️",
    "mixed herbs": "🌶️",
    "chilli powder": "🌶️",
    "chilli flakes": "🌶️",
    "curry powder": "🌶️",
    "garam masala": "🌶️",
    "bay leaf": "🌶️",
    "bay leaves": "🌶️",
    "cayenne": "🌶️",
    "coriander seeds": "🌶️",
    "ground coriander": "🌶️",
    "five spice": "🌶️",
    "star anise": "🌶️",
    "cardamom": "🌶️",
    # 🥤 Drinks
    "orange juice": "🥤",
    "apple juice": "🥤",
    "juice": "🥤",
    "squash": "🥤",
    "sparkling water": "🥤",
    "cola": "🥤",
    "lemonade": "🥤",
    "beer": "🥤",
    "wine": "🥤",
    "red wine": "🥤",
    "white wine": "🥤",
    "coffee": "🥤",
    "tea": "🥤",
    "tea bags": "🥤",
    # 🍫 Snacks
    "chocolate": "🍫",
    "dark chocolate": "🍫",
    "crisps": "🍫",
    "biscuits": "🍫",
    "crackers": "🍫",
    "popcorn": "🍫",
    "sweets": "🍫",
    "granola bar": "🍫",
    # 🧊 Frozen
    "frozen peas": "🧊",
    "peas": "🧊",
    "frozen sweetcorn": "🧊",
    "ice cream": "🧊",
    "frozen berries": "🧊",
    "fish fingers": "🧊",
    "frozen spinach": "🧊",
    "puff pastry": "🧊",
    "shortcrust pastry": "🧊",
    "frozen chips": "🧊",
    "oven chips": "🧊",
    # 🧴 Household
    "bin bags": "🧴",
    "kitchen roll": "🧴",
    "toilet roll": "🧴",
    "washing up liquid": "🧴",
    "dishwasher tablets": "🧴",
    "laundry detergent": "🧴",
    "sponges": "🧴",
    "foil": "🧴",
    "cling film": "🧴",
    "baking paper": "🧴",
    # 🧼 Toiletries
    "soap": "🧼",
    "hand soap": "🧼",
    "shower gel": "🧼",
    "body wash": "🧼",
    "bubble bath": "🧼",
    "shampoo": "🧼",
    "conditioner": "🧼",
    "razor": "🧼",
    "razor blades": "🧼",
    "shaving foam": "🧼",
    "shaving gel": "🧼",
    "deodorant": "🧼",
    "toothpaste": "🧼",
    "toothbrush": "🧼",
    "mouthwash": "🧼",
    "dental floss": "🧼",
    "moisturiser": "🧼",
    "moisturizer": "🧼",
    "hand cream": "🧼",
    "sun cream": "🧼",
    "suncream": "🧼",
    "lip balm": "🧼",
    "face wash": "🧼",
    "cotton wool": "🧼",
    "cotton buds": "🧼",
    "wet wipes": "🧼",
    "baby wipes": "🧼",
    "tissues": "🧼",
    "nappies": "🧼",
    "tampons": "🧼",
    "sanitary pads": "🧼",
    "plasters": "🧼",
    "paracetamol": "🧼",
    "ibuprofen": "🧼",
}


def guess_aisle(ingredient_name: str) -> str:
    """Best-effort aisle for an ingredient name; ❓ when we don't know."""
    name = ingredient_name.lower().strip()
    if name in _KEYWORDS:
        return _KEYWORDS[name]
    words = set(name.split())
    best: tuple[int, str] | None = None
    for keyword, emoji in _KEYWORDS.items():
        # multi-word keywords match as substrings, single words whole-word only
        matched = keyword in name if " " in keyword else (keyword in words or singular_match(keyword, words))
        if matched and (best is None or len(keyword) > best[0]):
            best = (len(keyword), emoji)
    return best[1] if best else UNKNOWN_AISLE


def singular_match(keyword: str, words: set[str]) -> bool:
    return any(word.rstrip("s") == keyword or keyword.rstrip("s") == word for word in words)


def is_valid_aisle(emoji: str) -> bool:
    return emoji in AISLE_ORDER
